---
title: "EDA_Chocolate"
author: "Manvir Kohli"
date: "2022-11-18"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Loading essential libraries
```{r Reading libraries}
## NOTE: uncomment the line below if you don't have the caTools library installs
library(dplyr)
library(tidyverse)
library(caTools)
```

Reading the data and splitting it into train and test datasets
```{r Loading data and creating train-test splits}
chocolate_data = read_csv(file= "../data/raw/chocolate.csv")
head(chocolate_data)
nrow(chocolate_data)
# # creating a train_test split of 70-30
set.seed(522)
sample <- sample.split(Y = chocolate_data$rating, SplitRatio = 0.7)  

# check if sample is true 
train_df  <- subset(chocolate_data, sample == TRUE)
test_df   <- subset(chocolate_data, sample == FALSE)

dim(train_df)
dim(test_df)
(nrow(train_df) + nrow(test_df) == nrow(chocolate_data)) 

write_csv(train_df,"../data/raw/train_df.csv")
write_csv(test_df,"../data/raw/test_df.csv")

```
